[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "SAURbWr37gXUYK9a15ppcppys1ktnmyVDFkCCyC2ePn"
vesting = "SAURWKPfnsLs3MmDkR3uGTyZuCdn4re5bzZQrZkrTe5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
