[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
swap = "SAURapcU2gKQvUDByeq3NKGwuaSCvYdwMGJ3nrSTgHm"
vesting = "SAURGZTwnVRzp85TcuKiENjZxF4x7VnSvPGCzW8MsWv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
